version: 2
updates:
  # https://github.com/dependabot/dependabot-core/issues/1297
  #  - package-ecosystem: npm
  #    directory: /
  #    schedule:
  #      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
